version: '3.8'

services:
  app:
    build: .
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - financial_data:/app/financial_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  financial_data: 